apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: task2-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task2-app
  template:
    metadata:
      labels:
        app: task2-app
    spec:
      containers:
        - name: app-container
          image: 489994096722.dkr.ecr.us-east-2.amazonaws.com/task2-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "terraform-20251027094124891200000006.cozzdxzyun2d.us-east-2.rds.amazonaws.com"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: task2-app
spec:
  type: ClusterIP
  selector:
    app: task2-app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
