name: CI/CD - Build & Deploy to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  ECR_REPO: 489994096722.dkr.ecr.us-east-2.amazonaws.com/task2-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # ✅ Use latest version for AWS credentials action
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::489994096722:role/Saad-Trustpolicy-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          ECR_REGISTRY="${ECR_REPO%/*}"
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build, tag, and push Docker image
        run: |
          docker build -t $ECR_REPO:$IMAGE_TAG ./src
          docker push $ECR_REPO:$IMAGE_TAG

      - name: Print image URL
        run: echo "Image pushed to $ECR_REPO:$IMAGE_TAG"

      - name: Install kubectl
        run: |
          curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.33.5/2024-10-09/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name Saad-EKS-Cluster
          kubectl config current-context
          kubectl get nodes

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/app-deployment app-container=${ECR_REPO}:${IMAGE_TAG} --namespace default
          kubectl rollout status deployment/app-deployment --namespace default -w
