name: CI/CD - Build & Deploy to EKS

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  ECR_REPO: 489994096722.dkr.ecr.us-east-1.amazonaws.com/task2-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::489994096722:role/Saad-Trustpolicy-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          ECR_REGISTRY="${ECR_REPO%/*}"
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build, tag, and push Docker image
        run: |
          docker build -t $ECR_REPO:$IMAGE_TAG .
          docker push $ECR_REPO:$IMAGE_TAG

      - name: Print image URL
        run: echo "Image pushed to $ECR_REPO:$IMAGE_TAG"



      # - name: Set up kubectl
      #   uses: azure/setup-kubectl@v3
      #   with:
      #     version: '1.27.0'

      # - name: Update kubeconfig
      #   run: |
      #     aws eks update-kubeconfig --region $AWS_REGION --name Saad-EKS-Cluster

      # - name: Deploy to k8s (update image)
      #   run: |
      #     kubectl set image deployment/app-deployment app-container=${ECR_REPO}:${IMAGE_TAG} --namespace default
      #     kubectl rollout status deployment/app-deployment --namespace default -w
